### ISSUE TITLE
nss-gk-api v0.2.1 Build issues on macOS

### ISSUE THREAD

**Issue by andreydanil** [mozilla/nss-gk-api#6]
I'm having issues with building this library on macOS Monterey (12.6.1).

```
python --version
Python 3.10.8
```

```
cargo --version
cargo 1.65.0 (4bc8f24d3 2022-10-20)
```

Trace:

```
nss-gk-api git:(main) cargo build               
   Compiling nss-gk-api v0.2.1 (/Users/x/development/github/nss-gk-api)
error: failed to run custom build command for `nss-gk-api v0.2.1 (/Users/x/development/github/nss-gk-api)`

Caused by:
  process didn't exit successfully: `/Users/x/development/github/nss-gk-api/target/debug/build/nss-gk-api-fc814944d6f2fe25/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=/Users/x/development/github/nss-gk-api/target/debug/build/nss-gk-api-d8907617f5c0c50b/out/nss

  --- stderr
  thread 'main' panicked at 'NSS build failed', build.rs:161:5
  stack backtrace:
     0:        0x105036098 - std::backtrace_rs::backtrace::libunwind::trace::h72c73b9e5db0005d
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:        0x105036098 - std::backtrace_rs::backtrace::trace_unsynchronized::h0241cec881bc8f92
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:        0x105036098 - std::sys_common::backtrace::_print_fmt::h7a7ee67e414bd3d7
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:66:5
     3:        0x105036098 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2990a6f24ccff6db
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:45:22
     4:        0x105050b04 - core::fmt::write::h91497fd291c8b104
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/fmt/mod.rs:1202:17
     5:        0x105032f78 - std::io::Write::write_fmt::h23fa41342cffacf4
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/io/mod.rs:1679:15
     6:        0x105037674 - std::sys_common::backtrace::_print::h39f712a9b74dd89c
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:48:5
     7:        0x105037674 - std::sys_common::backtrace::print::h0be19d9a7285bd90
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:35:9
     8:        0x105037674 - std::panicking::default_hook::{{closure}}::hb41cdb784f4c17ac
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:295:22
     9:        0x105037398 - std::panicking::default_hook::hdfe992d5fb29a991
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:314:9
    10:        0x105037c0c - std::panicking::rust_panic_with_hook::h2eb0e4b718773521
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:698:17
    11:        0x104af9ff4 - std::panicking::begin_panic::{{closure}}::h7cd28e2fc4a56403
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:617:9
    12:        0x104af9d34 - std::sys_common::backtrace::__rust_end_short_backtrace::h2cfbb1cdae948bbf
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
    13:        0x105059188 - std::panicking::begin_panic::hf4ab75903f9aa639
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:616:12
    14:        0x104ab4a38 - build_script_build::build_nss::h32c70286bf473b03
                                 at /Users/danilkov/development/github/nss-gk-api/build.rs:161:5
    15:        0x104ab6448 - build_script_build::setup_standalone::h02064a405d37e52f
                                 at /Users/danilkov/development/github/nss-gk-api/build.rs:295:5
    16:        0x104ab6e1c - build_script_build::main::h479f8078657a5745
                                 at /Users/danilkov/development/github/nss-gk-api/build.rs:433:9
    17:        0x104aa52ac - core::ops::function::FnOnce::call_once::h87c0658219210c46
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
    18:        0x104a8e568 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8a395664be6ccc6b
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:122:18
    19:        0x104abf46c - std::rt::lang_start::{{closure}}::h3d7647810aaa7200
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:166:18
    20:        0x10502f9e8 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h0c60ab225fafdaa1
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:283:13
    21:        0x10502f9e8 - std::panicking::try::do_call::he83c34dec7ecf156
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
    22:        0x10502f9e8 - std::panicking::try::hf8a127683312d6e6
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
    23:        0x10502f9e8 - std::panic::catch_unwind::h6bfb2185c735f4ae
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
    24:        0x10502f9e8 - std::rt::lang_start_internal::{{closure}}::he1235e45f833117a
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:148:48
    25:        0x10502f9e8 - std::panicking::try::do_call::h600fcfa83f96c092
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
    26:        0x10502f9e8 - std::panicking::try::h3ab439188ed13993
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
    27:        0x10502f9e8 - std::panic::catch_unwind::hb86c613836afcf80
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
    28:        0x10502f9e8 - std::rt::lang_start_internal::h94fa211da9d06d56
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:148:20
    29:        0x104abf434 - std::rt::lang_start::h922b132358ee7d92
                                 at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:165:17
    30:        0x104ab7204 - _main

```

Any advice? It is blocking the builds on https://github.com/mozilla/authenticator-rs/tree/ctap2-2021.

**Comment by andreydanil** [comment]
Solved it by following the [Building NSS](https://firefox-source-docs.mozilla.org/security/nss/build.html) guidelines.

On MacOS:
```
brew install mercurial git ninja python3-pip
python3 -m pip install gyp-next
```

It is also necessary to make sure that a python (not just python3) executable is in the path. The Homebrew Python installation has the necessary symlink but may require explicit adding to the PATH variable, for example like this:

```
export PATH="/opt/homebrew/opt/python/libexec/bin:$PATH"
```
